### PR TITLE
hide your own edits when listing edits

### PR DESCRIPTION
**Pull request by jnmtx**
changed "listedits" to list edits only by other users. "listalledits" shows all edits (even your own) -- same as listedits used to do. "listmyedits" lists only your own edits. To test.

### CODE REVIEW

**Comment by tannn** [comment]
@jnmtx thank you for your contribution. Have you already tested this functionality? If so, please upload logs or screenshots of the tests. Thanks.

**Comment by jnmtx** [comment]
Fixed bug (another commit now included in pull request). Time to set up test environment: 90 minutes. time to fix bug: 10 minutes. See screenshot. [http://imgur.com/Fcc7tLE](http://imgur.com/Fcc7tLE)

**Comment by tannn** [comment]
ok, thanks. I'll look into it and see about merging it soon.

**Comment by tannn** [comment]
Code review approved. Thanks for the contribution @jnmtx

**Pull request merged**
